# Generated by Django 3.1.6 on 2021-02-03 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_feedbackpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='EventProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(default='Not Set', max_length=5000)),
                ('speaker', models.TextField(default='Not Set', max_length=500)),
                ('comm_lead', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('prog_mgr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prog_mgr_proposal', to=settings.AUTH_USER_MODEL)),
                ('status_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.status')),
            ],
        ),
    ]
