# Generated by Django 3.1.6 on 2021-02-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210203_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventproposal',
            name='speaker',
            field=models.CharField(default='Not Set', max_length=100),
        ),
    ]
