# Generated by Django 3.1.6 on 2021-02-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_eventproposal_virtual'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue_platform',
            field=models.CharField(default='Not Set', max_length=100),
        ),
    ]
