# Generated by Django 3.1.6 on 2021-02-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_event_venue_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='speaker',
            field=models.CharField(default='Not Set', max_length=100),
        ),
    ]
