# Generated by Django 3.1.6 on 2021-02-03 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_event_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventproposal',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
