# Generated by Django 3.1.6 on 2021-02-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_eventproposal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventproposal',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
