# Generated by Django 3.1.6 on 2021-02-03 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_auto_20210204_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventproposal',
            name='comm_lead',
        ),
        migrations.AddField(
            model_name='eventproposal',
            name='comm_lead',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
